### PR TITLE
Create docker-compose file to test sample project

### LINKED ISSUE #51: Dockerize project
Could you dockerize project?

### PR DESCRIPTION
**Pull request by kakawait**
- [x] `README.md` in `cas-security-spring-boot-sample`
- [x] Add support for `security.cas.server.validation-base-url`
- [x] Add support for `security.cas.service.callback-base-url`
- [x] Create `Dockerfile` for sample
- [x] Create `docker-compose.yml` for sample
- [x] Upgrade `README.md` with new properties `security.cas.server.validation-base-url` & `security.cas.service.callback-base-url`
- [x] Docker healthcheck
- [x] Able to build image without maven central

fixes #51

### CODE REVIEW

**Comment by coskundeniz89** [comment]
It look good but did you try it? I think you can't access from browser. I will try tomorrow and connect with you.

**Comment by kakawait** [comment]
Yes I tried but may I miss something to push. I will be out until Monday. Will see just after.

**Comment by kakawait** [comment]
Just tried 

```
cd cas-security-spring-boot-sample
docker-compose up -d
# (wait until CAS server boot)
chrome http://localhost:8081
# -> get redirected to http://localhost:8080/cas/login?service=http%3A%2F%2Flocalhost%3A8081%2Flogin
# Fill the form with user: casuser & password: Mellon
# post form and get redirected to http://localhost:8081/
```

And you should have result page like following

screen shot 2017-08-29 at 09 30 39

---

@coskundeniz89 can you explain me where you get an issue ?

**Comment by kakawait** [comment]
Hum I think you can get an issue when building image related to https://github.com/kakawait/cas-security-spring-boot-starter/pull/60/files#diff-e94db4c674edc6c7ca3e97b11bf4141dR8 since `0.5.0` is pointing to the _maven central_ code and not code from that PR.

I will change that by upgrading version

**Comment by kakawait** [comment]
@coskundeniz89 you should try again but you have to re-build image (or to be safe simply delete older docker image previously created)

**Comment by kakawait** [comment]
@coskundeniz89 I added a basic `README.md` https://github.com/kakawait/cas-security-spring-boot-starter/blob/e00b8e721afc1d6c7f23b6607a16ca9edb7b8701/cas-security-spring-boot-sample/README.md

**Comment by kakawait** [comment]
@coskundeniz89 I added some fixes but tested from scratch using `develop` branch (with at least this commit b6b2631e08842952ccbb0a470653f166a1d6f1cc)

```
git checkout develop
git pull origin develop
cd cas-security-spring-boot-sample
docker-compose build --no-cache
docker-compose up -d
```

Works fine on 

- [x] docker-for-mac
- [ ] docker-for-win (currently in test, will be update soon)

**Pull request merged**
